In [1]:
from all import *

In [2]:
DOCUMENT_ORGANIZATION

     document_eu_id organization_abbr
0         PE680.868              TRAN
1         PE680.885              TRAN
2         PE680.905              TRAN
3         PE695.192              INTA
4         PE699.064              INTA
...             ...               ...
3419      PE745.351              TRAN
3420      PE662.009              AFET
3421      PE719.796              ECON
3422      PE729.817              BUDG
3423      PE745.281              CULT

[3424 rows x 2 columns]

``Ha ezt joinoljátok az edgelist-re a document_eu_id oszlopon, utána tudtok szakbizottságra szűrni." - Levi

In [3]:
COSPONSORSHIP_EDGELIST

,amendment_id,person_id,person_full_name,document_eu_id,procedure_interinst_id,date
0,18,1898,Ilana Cicurel,PE749.912,2022/0906(COD),2023-06-13
1,37,2002,Isabel Carvalhais,PE657.419,2020/0095(COD),2020-10-06
2,38,2002,Isabel Carvalhais,PE657.419,2020/0095(COD),2020-10-06
3,47,1369,Pascal Canfin,PE736.476,2021/0423(COD),2022-09-15
4,50,1369,Pascal Canfin,PE736.476,2021/0423(COD),2022-09-15
...,...,...,...,...,...,...
1172013,448512,216,Rovana Plumb,PE738.577,2021/0420(COD),2023-01-25
1172014,448512,2033,Andris Ameriks,PE738.577,2021/0420(COD),2023-01-25
1172015,448512,1955,Erik Bergkvist,PE738.577,2021/0420(COD),2023-01-25
1172016,448512,2383,Andreas Schieder,PE738.577,2021/0420(COD),2023-01-25
1172017,448512,1650,Maria Grapini,PE738.577,2021/0420(COD),2023-01-25

In [4]:
cosp = COSPONSORSHIP_EDGELIST
docorg = DOCUMENT_ORGANIZATION

In [5]:
cosp['document_eu_id'] = cosp['document_eu_id'].astype(str)
docorg['document_eu_id'] = docorg['document_eu_id'].astype(str)

In [6]:
docorg.dtypes

document_eu_id       object
organization_abbr    object
dtype: object

In [7]:
# idk why this gives an error
# maybe some pointer-related shenanigans ??
bigboy = docorg.join(cosp, on="document_eu_id")

ValueError: You are trying to merge on object and int64 columns. If you wish to proceed you should use pd.concat